#!/usr/bin/env bash

while IFS= read -r i; do
  # i='glowstoneGlowIcon'
  temp_file="MQ2.tmp.js"
  target_file="MQ2.js"
echo "${i//./'\.'}"
    sed "s/${i//./'\.'}/manager.${i##*.}/g" "$target_file" >"$temp_file" && mv "$temp_file" "$target_file"
    echo "Successfully updated MQ2.js using Enum.$v"
done <<"EOF"
Enum.Item.woodpile
Enum.Magic.window
Enum.Magic.weakenedGraphic
Enum.BatMes.currMes
Enum.Magic.refreshActive
Enum.Magic.fireTics
Enum.Icon.keyboard
Enum.Icon.keyboard
Enum.Icon.keyboard
Enum.Icon.checkDay
Enum.Skill.digits
Enum.Skill.digits
Enum.Skill.digits
Enum.Skill.digits
Enum.Char.state
Enum.Magic.weaknessTriggered
Enum.Skill.meditateActive
Enum.Char.state
Enum.Char.state
Enum.Char.state
Enum.Char.state
Enum.Magic.refreshArmorDelay
Enum.Magic.boltDelay
Enum.Magic.refreshFade
Enum.Magic.refreshFade
Enum.Magic.firewallFade
Enum.Magic.firewallFade
Enum.Skill.engaged
Enum.BatMes.currMes
Enum.Magic.weaknessTriggered
Enum.Magic.boostHits
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Icon.chillTics
Enum.Icon.chillTics
Enum.Magic.fireTics
Enum.Icon.chillTics
Enum.Icon.shieldBlocks
Enum.Magic.boostHits
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Icon.shieldBlocks
Enum.Magic.weaknessTriggered
Enum.Skill.engaged
Enum.Skill.engaged
Enum.Skill.engaged
Enum.Skill.engaged
Enum.Char.state
Enum.WizNumber.corWiz
Enum.Magic.refreshArmorPow
Enum.Icon.shieldBlocks
Enum.Char.state
Enum.Icon.chillTics
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Icon.chillTics
Enum.Icon.chillTics
Enum.Magic.fireTics
Enum.Magic.boostHits
Enum.Char.state
Enum.Char.state
Enum.Char.state
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Magic.boostHits
Enum.Magic.refreshTics
Enum.Magic.refreshActive
Enum.Icon.shieldBlocks
Enum.Magic.currUpgrade
Enum.Skill.engaged
Enum.Food.hotChocActive
Enum.Skill.engaged
Enum.Magic.fireTics
Enum.Food.hotChocActive
Enum.Skill.engaged
Enum.Skill.luckTics
Enum.Magic.refreshActive
Enum.Skill.collectorTics
Enum.Skill.meditateActive
Enum.Skill.engaged
Enum.Food.hotChocActive
Enum.Magic.weaknessTriggered
Enum.Food.hotChocActive
Enum.Char.state
Enum.Char.state
Enum.Magic.refreshGeneralTics
Enum.Magic.refreshTics
Enum.Magic.refreshStaffTics
Enum.Magic.fireTics
Enum.Icon.chillTics
Enum.Magic.weaknessTriggered
Enum.Skill.engaged
Enum.Icon.expHitBonus
Enum.BatMes.currMes
Enum.Icon.expBonus
Enum.Icon.expBonus
Enum.Magic.fireTics
Enum.Icon.chillTics
Enum.Char.state
Enum.Char.state
Enum.Magic.firePower
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Mob.mobVar
Enum.Icon.shieldBlocks
Enum.Magic.boostHits
Enum.Magic.weaknessTriggered
Enum.Magic.windowsOut
Enum.Icon.keys
Enum.Magic.refreshArmorPow
Enum.Icon.expHitBonus
Enum.Titles.defeated
Enum.Titles.gale
Enum.Titles.boyer
Enum.Titles.silvan
Enum.Titles.guyan
Enum.Titles.mutrovia
Enum.Titles.edelston
Enum.Titles.yukkan
Enum.Titles.harrakoth
Enum.Titles.ransiMoor
Enum.Titles.ryNolus
Enum.Titles.malMorra
Enum.Titles.upgradeStatsTitle
Enum.Titles.top10Title
Enum.Titles.ninjaMode
Enum.Titles.brymsol
Enum.Titles.loadingLegionData
Enum.Titles.shaydeTitle
Enum.Titles.grottoTitle
Enum.Titles.unbrokenTitle
Enum.TransLocas.transGale
Enum.TransLocas.transSilvan
Enum.TransLocas.transOllusara
Enum.TransLocas.transEdelston
Enum.TransLocas.transYukkan
Enum.TransLocas.transRansi
Enum.TransLocas.transMorra
Enum.Char.state
Enum.Magic.refreshArmorDelay
Enum.Magic.refreshArmorPow
Enum.Mob.mobVar
Enum.Icon.expBonus
Enum.Skill.luckTics
Enum.Skill.collectorTics
Enum.Magic.fireTics
Enum.Icon.chillTics
Enum.Magic.refreshTics
Enum.Magic.refreshStaffTics
Enum.Magic.refreshGeneralTics
Enum.Magic.boltDelay
Enum.BatMes.currMes
Enum.Skill.digits
Enum.Icon.shieldBlocks
Enum.Magic.boostHits
Enum.Magic.currUpgrade
Enum.Magic.firePower
Enum.Magic.windowsOut
Enum.WizNumber.corWiz
Enum.Magic.firewallFade
Enum.Magic.refreshActive
Enum.Skill.meditateActive
Enum.Skill.engaged
Enum.Icon.checkDay
Enum.Magic.refreshFade
Enum.Food.hotChocActive
Enum.Titles.defeatedSound
Enum.Icon.explodeSound
Enum.Magic.boltSound
Enum.Magic.guardChar
Enum.Item.woodpile
Enum.Magic.weakenedGraphic
Enum.Magic.weaknessTriggered
Enum.Icon.keyboard
Enum.Magic.window
EOF
